sudo: false
cache: pip
language: python
python:
- '2.7'

install:
    - pip install $TRAVIS_BUILD_DIR

script:
    - travis-sphinx build --source=test/docs/source
    - travis-sphinx deploy --pullrequests
