language: python - "2.7"
sudo: false

install:
    - pip install --user git+https://github.com/Syntaf/travis-sphinx.git
    - export PATH=$HOME/.local/bin:$PATH

script:
    - travis-sphinx --pullrequests --source=test/docs/source build
    - travis-sphinx deploy
